image:
  repository: docker.io/guscontre1/ocp-dog-frontend-api
  tag: "2"

service:
  port: 5001
  targetPort: 5001

env:
  BACKEND_URL: http://ocp-dog-backend-api.guscontre-dev.svc.cluster.local:5002/dog
  ALLOWED_ORIGINS: "*"
